### ISSUE TITLE
Adding edgetest for automated dependency management

### ISSUE THREAD

**Issue by fdosani** [capitalone/synthetic-data#240]
Hey there, 

Wondering if the @capitalone/synthetic-data-admin-team would be open to me submitting a PR for adding in edgetest. I see the dependencies are pinned, `edgetest` would provide a range and continuously keep bumping up as along as the testing passed?

I'd be happy to submit a PR to include the functionality if the team is open to this?

**Comment by cbbruss** [comment]
I don't see why not. @rreilly10 / @tazitoo?

**Comment by tazitoo** [comment]
We have pending PRs to merge once white bolt scanning works.  The PRs significantly reduce our dependence on external packages, and will be moving away from pinning the few remaining dependencies.  Not sure we will need edgetest at that point.

**Comment by fdosani** [comment]
Sure np. Will close out this issue then.
