### ISSUE TITLE
Sythetic Data uses DataProfiler ; but pins scipy==1.8.0 while dataprofiler uses scipy>=1.10.0

### ISSUE THREAD

**Issue by rxm7706** [capitalone/synthetic-data#340]
**General Information:**
 - OS: Linux
 - Python version: 3.10
 - Library version: dataprofiler=0.10.5 &  synthetic-data=1.2.1

**Describe the bug:**
Dependencies of synthetic data are scipy==1.8.0  and dataprofiler, but DataProfiler has scipy>=1.10.0
```
numpy>=1.22
scikit-learn>=1.1.0
scipy==1.8.0
dataprofiler>=0.8.8
```
https://github.com/capitalone/DataProfiler/blob/main/requirements.txt#L13
`scipy>=1.10.0`
https://github.com/capitalone/synthetic-data/blob/main/requirements.txt#L3
```
scipy==1.8.0
dataprofiler>=0.8.8
```
https://github.com/capitalone/DataProfiler/blob/main/requirements-ml.txt#L1
`scikit-learn>=0.23.2`

To use these the two together - DataProfiler[full] + synthetic-data
1) probably makes sense to remove scipy from synthetic (it will inherit and match the needed dependency form data profiler. 
2) If we want to retain scipy, we should make it >=1.10.0 and that will atleast ensures pip manages to resolve faster without overriding 

**To Reproduce:**

**Expected behavior:**

**Screenshots:**

**Additional context:**
https://github.com/capitalone/synthetic-data/pull/342

**Comment by rxm7706** [comment]
@taylorfturner - Do you have any idea when the next release is planned for - Just trying to get an idea of when this change will make it to PyPi. Thank you.

**Comment by taylorfturner** [comment]
Hey @rxm7706 -- thanks for the ping. Yes, next week we will be doing a deployment of capitalone/DataProfiler -- can probably do a release of this repo as well. Thanks!

**Comment by taylorfturner** [comment]
@rxm7706 Release conducted last week. Thanks!
